### ISSUE TITLE
Fix code snippets in blog posts 

### ISSUE THREAD

**Issue by codergrl** [dymaptic/GeoBlazor#105]
The blog posts have code snippets in them that do not match since the renaming. They need to be updated with the correct snippets.

**Comment by TimPurdum** [comment]
@codergrl I updated https://www.dymaptic.com/arcgis-in-asp-net-blazor-no-javascript-required/. I don't see other links/snippets that need updating, I think that's the only one?

**Comment by codergrl** [comment]
👍🏻
