### ISSUE TITLE
API Key not working in WASM app

### ISSUE THREAD

**Issue by codergrl** [dymaptic/GeoBlazor#106]
I have 2 apps set up identically, one is Server one is WASM. In the Server app, the API Key is recognized and I can see a map. In the WASM app, I get the message about the API key not being found.

**WASM csproj file**
```
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>30c514f2-c61c-49c2-a3f5-cc9f14a2d8e2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dymaptic.GeoBlazor.Core" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="6.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="6.0.11" PrivateAssets="all" />
  </ItemGroup>

</Project>
```
**Server csproj file**
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1825f0da-0cff-4320-9bb8-aca4793b6f72</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dymaptic.GeoBlazor.Core" Version="1.1.1" />
  </ItemGroup>

</Project>
```

**secrets.json in folders 30c514f2-c61c-49c2-a3f5-cc9f14a2d8e2 and 1825f0da-0cff-4320-9bb8-aca4793b6f72**
```json
{
  "ArcGISApiKey": "AAPK2e**********************************************tIn3Y54"
}
```

**Comment by TimPurdum** [comment]
@codergrl we can add documentation, but user secrets are not  supported in wasm. [This gIssue](https://github.com/dotnet/aspnetcore/issues/25893) gives more details as to why. In the samples app, there is a field for a user to enter the API Key manually. You can also set up an OAuth or custom scheme, as we have documented on the [Authentication](https://docs.geoblazor.com/pages/authentication.html) docs page.

**Comment by codergrl** [comment]
Ah, yes, that makes sense, because wasm app is downloaded locally. We should add stuff to our doc that explains this and update the blog post with a link to the Auth section in the doc so ppl do not go down my path and give up using it when that doesn't work.
