### ISSUE TITLE
Check on and Complete `Portal` Implementation

### ISSUE THREAD

**Issue by morehavoc** [dymaptic/GeoBlazor#144]
We have `Portal` (for setting the URL) implemented for basemaps, but not other things that can support an item. We want to support this to that a person could use their own portal and not just ArcGIS.com.  See this example from discord:
![image](https://user-images.githubusercontent.com/1805118/224387424-d23c72a5-da77-4021-975e-c5f634696c95.png)

**Comment by TimPurdum** [comment]
@morehavoc I got this far with testing. I think this is something we would need to open up on our Enterprise server, to use the test layer we discussed.

> Access to fetch at 'https://arcgis.dymaptic.com/sharing/rest/portals/self?f=json&culture=en-us' from origin 'https://localhost:7255' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
