### ISSUE TITLE
Adding points via code failing, calling Clear() on GraphicsLayer throws a Microsoft.JSInterop error

### ISSUE THREAD

**Issue by anotherlab** [dymaptic/GeoBlazor#152]
I'm trying to add points and lines to a map.  When I add the points, it usually works for the first time the app is compiled. When I stop and restart the app, the code to add the points does not report any error, but the points are not visible. They are in the GraphicsLayer.Graphics collection.

If I call the Clear method of the GraphicsLayer, it will crash with the following error:

```
{"Value cannot be null. (Parameter 'jsObjectReference')"}
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2147467261
    HelpLink: null
    InnerException: null
    Message: "Value cannot be null. (Parameter 'jsObjectReference')"
    ParamName: "jsObjectReference"
    Source: "Microsoft.JSInterop"
    StackTrace: "   at Microsoft.JSInterop.JSObjectReferenceExtensions.<InvokeVoidAsync>d__0.MoveNext()\r\n   at dymaptic.GeoBlazor.Core.Components.Layers.GraphicsLayer.<Clear>d__11.MoveNext()\r\n   at demo1.Pages.Map1.<AddPoints>d__6.MoveNext() in D:\\dev\\maui\\GeoBlazor\\demo1\\demo1\\Pages\\Map1.razor:line 64"
    TargetSite: {Void MoveNext()}
```

I do not know if these are bugs or if my implementation is flawed.

This is the core of what I am try to do
```XML
<MapView Longitude="_longitude" Latitude="_latitude" Zoom="11" Style="height: 600px; width: 100%;">
    <Map ArcGisDefaultBasemap="arcgis-navigation">
        <GraphicsLayer @ref="pointsLayer">
        </GraphicsLayer>
    </Map>
</MapView>
```

```C#
List<Graphic> mapPoints = new();

foreach (var point in points)
{
  var g = new Graphic(
    new Point(point.Longitude, point.Latitude),
    new SimpleMarkerSymbol(new Outline(new MapColor("white"), 1.0), new MapColor("red")));

  mapPoints.Add(g);
}

pointsLayer.Clear();

await pointsLayer.Add(mapPoints);
```

I have created a standalone app to demonstrate both problems. The repo is https://github.com/anotherlab/GeoBlazor-issue-1. You will need to add your own ESRI API key and that information is included in the README.md file.

Tested under Windows 11 with Windows and Android as target platforms. Compiled with VS 2022 17.5.3 and GeoBlazor 2.0.1

**Comment by TimPurdum** [comment]
@anotherlab thanks for the clear issue and reproduction sample! I am looking into this, will let you know what I find.

**Comment by TimPurdum** [comment]
Both these issues have the same root cause. In order to facilitate communication between JS and .NET, we need to round-trip references to the `GraphicsLayer`. The return-trip sets the `Js Apparently, on first load of a MAUI WebView, we have a race condition that is preventing that from happening. I think I have already discovered a fix for it, basically moving an event listener earlier in the setup cycle. I just need to verify that that doesn't break anything else.

There is no good workaround I can find, I will try to push out a beta build with this fix this weekend.

**Comment by TimPurdum** [comment]
@anotherlab please try updating to this nuget package https://www.nuget.org/packages/dymaptic.GeoBlazor.Core/2.0.2-beta-1 and see if it resolves the issue.

**Comment by anotherlab** [comment]
@TimPurdum It looks like [2.0.2 Beta 1](https://www.nuget.org/packages/dymaptic.GeoBlazor.Core/2.0.2-beta-1) addressed both issues.
