### ISSUE TITLE
PictureMarkerSymbols with offsets are being placed on the map without the offsets being used

### ISSUE THREAD

**Issue by anotherlab** [dymaptic/GeoBlazor#154]
If you add a PictureMarkerSymbol with xOffset and/or yOffset values, they are not used and the symbol appears to be drawn with offsets of 0.0, 0.0

In the screenshot show below, the blue marker uses no offsets, the green marker uses positive offsets, and the red marker uses negative offset.  They all appear as if they uses 0 for the offset values

![image](https://user-images.githubusercontent.com/1191188/229600369-d925c33d-8f2c-42ce-9bcb-e34669dd2066.png)

I have created a standalone app to demonstrate the problem. The repo is https://github.com/anotherlab/geoblazer-issue-2-marker-offsets. You will need to add your own ESRI API key and that information is included in the README.md file.

Tested under Windows 11 with Windows and Android as target platforms. Compiled with VS 2022 17.5.3 and GeoBlazor 2.0.2-Beta 2

**Comment by TimPurdum** [comment]
@anotherlab found the issue, stupid simple, `xoffset` where it should be `xOffset`. Unfortunately we tend to lose string safety when crossing the border between C# and JS. I will let you know as soon as there is a beta or release with a fix.
