### ISSUE TITLE
Calling a page with routing parameters causes the map to not initialize correctly

### ISSUE THREAD

**Issue by anotherlab** [dymaptic/GeoBlazor#155]
If a GeoBlazor map is on a page that uses routing to pass in a parameter, the map is not initialized correctly.  Invoking a map before using route parameters will allow the map to display correctly.  Calling the page without passing in the parameter as part of the route allows the map to initialize correctly. Passing in parameters as query strings also works correctly.

I have updated the demo from a previous issue to demonstrate the problem. The repo is https://github.com/anotherlab/geoblazer-issue-2-marker-offsets. You will need to add your own Esri API key and that information is included in the README.md file.

## What is happening ##
When a page is invoked with a parameter passed in as part of the route, no map details are displayed and numerous Javascript errors can be seen in the browser console log

## What should happen ##
The map should be displayed.

## Steps to replicate the problems ##
1. Clone or get the latest version of the [demo](https://github.com/anotherlab/geoblazer-issue-2-marker-offsets)
2. Restore the nuget packages
3. Edit [MauiProgram.cs](https://github.com/anotherlab/GeoBlazor-issue-1/blob/main/demo1/MauiProgram.cs#L22) and replace "INSERT-YOUR-ESRI-API-KEY-HERE" with your API key
4. Build and the run app on the platform of your choice
5. Click on the link labeled "Route param". This must be the first page invoked.

When viewed with Chrome Inspect the following Javascript errors come up in the log
<details>
<summary>Error log</summary

```
arcGisJsInterop.js:52          GET https://0.0.0.0/pageroute/student/_content/dymaptic.GeoBlazor.Core/assets/esri/widgets/Popup/t9n/Popup_en.json 404 (Not found)
arcGisJsInterop.js:52          GET https://0.0.0.0/pageroute/student/_content/dymaptic.GeoBlazor.Core/assets/esri/t9n/common_en.json 404 (Not found)
arcGisJsInterop.js:52          GET https://0.0.0.0/pageroute/student/_content/dymaptic.GeoBlazor.Core/assets/esri/widgets/Attribution/t9n/Attribution_en.json 404 (Not found)
arcGisJsInterop.js:52          GET https://0.0.0.0/pageroute/student/_content/dymaptic.GeoBlazor.Core/assets/esri/widgets/Zoom/t9n/Zoom_en.json 404 (Not found)
arcGisJsInterop.js:52          GET https://0.0.0.0/pageroute/student/_content/dymaptic.GeoBlazor.Core/assets/esri/widgets/ScaleBar/t9n/ScaleBar_en.json 404 (Not found)
arcGisJsInterop.js:52          GET https://0.0.0.0/pageroute/student/_content/dymaptic.GeoBlazor.Core/assets/esri/widgets/Popup/t9n/Popup.json 404 (Not found)
arcGisJsInterop.js:52          GET https://0.0.0.0/pageroute/student/_content/dymaptic.GeoBlazor.Core/assets/esri/t9n/common.json 404 (Not found)
arcGisJsInterop.js:52          GET https://0.0.0.0/pageroute/student/_content/dymaptic.GeoBlazor.Core/assets/esri/widgets/Attribution/t9n/Attribution.json 404 (Not found)
arcGisJsInterop.js:52          GET https://0.0.0.0/pageroute/student/_content/dymaptic.GeoBlazor.Core/assets/esri/widgets/Zoom/t9n/Zoom.json 404 (Not found)
arcGisJsInterop.js:52          GET https://0.0.0.0/pageroute/student/_content/dymaptic.GeoBlazor.Core/assets/esri/widgets/Compass/t9n/Compass_en.json 404 (Not found)
arcGisJsInterop.js:52          GET https://0.0.0.0/pageroute/student/_content/dymaptic.GeoBlazor.Core/assets/esri/widgets/ScaleBar/t9n/ScaleBar.json 404 (Not found)
arcGisJsInterop.js:74 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
arcGisJsInterop.js:52          GET https://0.0.0.0/pageroute/student/_content/dymaptic.GeoBlazor.Core/assets/esri/widgets/Compass/t9n/Compass.json 404 (Not found)
arcGisJsInterop.js:1 [esri.widgets.Popup] widget-intl:locale-error esri.widgets.Popup pe {name: 'intl:message-bundle-error', details: {…}, message: 'Errors occurred while loading "esri/widgets/Popup/t9n/Popup"'}
arcGisJsInterop.js:1 [esri.widgets.Popup] widget-intl:locale-error esri.widgets.Popup pe {name: 'intl:message-bundle-error', details: {…}, message: 'Errors occurred while loading "esri/t9n/common"'}
arcGisJsInterop.js:1 [esri.widgets.Attribution] widget-intl:locale-error esri.widgets.Attribution pe {name: 'intl:message-bundle-error', details: {…}, message: 'Errors occurred while loading "esri/widgets/Attribution/t9n/Attribution"'}
arcGisJsInterop.js:1 [esri.widgets.Zoom] widget-intl:locale-error esri.widgets.Zoom pe {name: 'intl:message-bundle-error', details: {…}, message: 'Errors occurred while loading "esri/widgets/Zoom/t9n/Zoom"'}
arcGisJsInterop.js:1 [esri.widgets.ScaleBar] widget-intl:locale-error esri.widgets.ScaleBar pe {name: 'intl:message-bundle-error', details: {…}, message: 'Errors occurred while loading "esri/widgets/ScaleBar/t9n/ScaleBar"'}
arcGisJsInterop.js:1 [esri.widgets.Compass] widget-intl:locale-error esri.widgets.Compass pe {name: 'intl:message-bundle-error', details: {…}, message: 'Errors occurred while loading "esri/widgets/Compass/t9n/Compass"'}
arcGisJsInterop.js:52 TypeError: Cannot destructure property 'zoomIn' of 'this.messages' as it is null.
    at o.render (arcGisJsInterop.js:10571:172038)
    at s (arcGisJsInterop.js:52:18720)
    at ZA (arcGisJsInterop.js:1:666288)
    at render (arcGisJsInterop.js:52:19121)
    at p (arcGisJsInterop.js:29:27361)
    at Object.merge (arcGisJsInterop.js:29:27973)
    at o._attach (arcGisJsInterop.js:52:21240)
    at _internalHandles.add.Ea.initial (arcGisJsInterop.js:52:21173)
    at arcGisJsInterop.js:28:96162
    at w3t (arcGisJsInterop.js:28:96244)
arcGisJsInterop.js:52 TypeError: Cannot read properties of null (reading 'mi')
    at o._renderLine (arcGisJsInterop.js:10581:44897)
    at o.render (arcGisJsInterop.js:10581:44020)
    at s (arcGisJsInterop.js:52:18720)
    at ZA (arcGisJsInterop.js:1:666288)
    at render (arcGisJsInterop.js:52:19121)
    at p (arcGisJsInterop.js:29:27361)
    at Object.merge (arcGisJsInterop.js:29:27973)
    at o._attach (arcGisJsInterop.js:52:21240)
    at _internalHandles.add.Ea.initial (arcGisJsInterop.js:52:21173)
    at arcGisJsInterop.js:28:96162
arcGisJsInterop.js:52 TypeError: Cannot read properties of null (reading 'reset')
    at o.render (arcGisJsInterop.js:10571:164726)
    at s (arcGisJsInterop.js:52:18720)
    at ZA (arcGisJsInterop.js:1:666288)
    at render (arcGisJsInterop.js:52:19121)
    at p (arcGisJsInterop.js:29:27361)
    at Object.merge (arcGisJsInterop.js:29:27973)
    at o._attach (arcGisJsInterop.js:52:21240)
    at _internalHandles.add.Ea.initial (arcGisJsInterop.js:52:21173)
    at arcGisJsInterop.js:28:96162
    at w3t (arcGisJsInterop.js:28:96244)
arcGisJsInterop.js:1 [esri.core.workers.WorkerOwner] ErrorEvent {isTrusted: true, message: "Uncaught NetworkError: Failed to execute 'importSc…sri/core/workers/RemoteClient.js' failed to load.", filename: 'blob:https://0.0.0.0/b0d0b20b-9aec-4bd5-b858-aa47c64f7a59', lineno: 1, colno: 4171, …}
arcGisJsInterop.js:1 [esri.core.workers.WorkerOwner] ErrorEvent {isTrusted: true, message: "Uncaught NetworkError: Failed to execute 'importSc…sri/core/workers/RemoteClient.js' failed to load.", filename: 'blob:https://0.0.0.0/b0d0b20b-9aec-4bd5-b858-aa47c64f7a59', lineno: 1, colno: 4171, …}
arcGisJsInterop.js:1 [esri.core.workers.WorkerOwner] ErrorEvent {isTrusted: true, message: "Uncaught NetworkError: Failed to execute 'importSc…sri/core/workers/RemoteClient.js' failed to load.", filename: 'blob:https://0.0.0.0/b0d0b20b-9aec-4bd5-b858-aa47c64f7a59', lineno: 1, colno: 4171, …}
arcGisJsInterop.js:10571 Uncaught (in promise) TypeError: Cannot destructure property 'zoomIn' of 'this.messages' as it is null.
    at o.render (arcGisJsInterop.js:10571:172038)
    at s (arcGisJsInterop.js:52:18720)
    at ZA (arcGisJsInterop.js:1:666288)
    at render (arcGisJsInterop.js:52:19121)
    at p (arcGisJsInterop.js:29:27361)
    at Object.merge (arcGisJsInterop.js:29:27973)
    at o._attach (arcGisJsInterop.js:52:21240)
    at _internalHandles.add.Ea.initial (arcGisJsInterop.js:52:21173)
    at arcGisJsInterop.js:28:96162
    at w3t (arcGisJsInterop.js:28:96244)
arcGisJsInterop.js:10581 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'mi')
    at o._renderLine (arcGisJsInterop.js:10581:44897)
    at o.render (arcGisJsInterop.js:10581:44020)
    at s (arcGisJsInterop.js:52:18720)
    at ZA (arcGisJsInterop.js:1:666288)
    at render (arcGisJsInterop.js:52:19121)
    at p (arcGisJsInterop.js:29:27361)
    at Object.merge (arcGisJsInterop.js:29:27973)
    at o._attach (arcGisJsInterop.js:52:21240)
    at _internalHandles.add.Ea.initial (arcGisJsInterop.js:52:21173)
    at arcGisJsInterop.js:28:96162
arcGisJsInterop.js:10571 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'reset')
    at o.render (arcGisJsInterop.js:10571:164726)
    at s (arcGisJsInterop.js:52:18720)
    at ZA (arcGisJsInterop.js:1:666288)
    at render (arcGisJsInterop.js:52:19121)
    at p (arcGisJsInterop.js:29:27361)
    at Object.merge (arcGisJsInterop.js:29:27973)
    at o._attach (arcGisJsInterop.js:52:21240)
    at _internalHandles.add.Ea.initial (arcGisJsInterop.js:52:21173)
    at arcGisJsInterop.js:28:96162
    at w3t (arcGisJsInterop.js:28:96244)
```
<details>

Tested under Windows 11 with Windows and Android as target platforms. Compiled with VS 2022 17.5.3 and GeoBlazor 2.0.2-Beta 2

**Comment by morehavoc** [comment]
Bringing over the discord discussion

> Oh... I've seen something similar to this before. In the chrome errors in the gissue, it looks like it's trying to pull the _content directory from the wrong place. it's doing this: https://0.0.0.0/pageroute/student/_content/dymaptic.GeoBlazor.Core/assets/esri/widgets/Popup/t9n/Popup_en.json  when it should be doing this (or something like it): https://0.0.0.0/_content/dymaptic.GeoBlazor.Core/assets/esri/widgets/Popup/t9n/Popup_en.json  I'm trying to find where we talked about that before.
here we go, could it be this: https://discord.com/channels/1027907220949717033/1065702132658999387/1065761715029020714
anotherlab
OP
 — Today at 1:26 PM
@morehavoc Yep, that was the right post. Adding  the config key of "ArcGISAssetsPath" with the value "/_content/dymaptic.GeoBlazor.Core/assets" appears to have fixed the problem with our app.  Thank you for the quick response. Will the value of ArcGISAssetsPath be updated in future release to remove the leading "."?
morehavoc — Today at 1:26 PM
We have discussed it, and there was some reason that we left it, so we should revisit it.
anotherlab
OP
 — Today at 1:27 PM
Does that mean that there are side affects for that change that we should be aware of?
morehavoc — Today at 1:28 PM
apparently we didn't write this down, which is embarrassing. But as I recall, it had to do with something in blazor server specifically. @Tim, Chief BlazorBuilder do you remember?
oh... I think, maybe, in blazor server it has to do with specifying <base href="/" />
anotherlab
OP
 — Today at 1:34 PM
We are using <base href="/" /> in our mobile/web app
Tim, Chief BlazorBuilder — Today at 1:35 PM
huh, yeah, I thought that fixed all those kinds of errors.
@anotherlab can you tell if the bug is mobile specific?
morehavoc — Today at 1:36 PM
It's not, I encountered this in a WASM app where the map was on a page and not on the root: https://discord.com/channels/1027907220949717033/1065702132658999387/1065761715029020714
I kind of suspect that we should just pull that . out.
Tim, Chief BlazorBuilder — Today at 1:39 PM
lol, nice, I gave that a thumbs up and promptly forgot. But I wouldn't be surprised if removing the dot breaks other scenarios.
morehavoc — Today at 1:40 PM
I don't think there are any side affects to setting this. That is actually flowing through to a setting in the ArcGIS api itself. So once it's happy about loading the source files, it should all be fine.
Tim, Chief BlazorBuilder — Today at 1:41 PM
Yes, overriding that setting was intentionally supported, so you should be good with manually setting it for now, @anotherlab

**Comment by morehavoc** [comment]
I think that the decision is that we should remove the `.` from the default URL. However, we should confirm that removing the dot doesn't break other platforms. We might even want to set some different defaults depending on the platform. @TimPurdum

**Comment by anotherlab** [comment]
@morehavoc What would be the reason for having different default URLs for different platforms? I thought the root cause of the problem is when you use routing with parameters. That's not platform specific.

**Comment by morehavoc** [comment]
Well, @TimPurdum mentioned he thought just changing it would break things elsewhere, hence my comment about testing to see if we need the ‘.’

**Comment by TimPurdum** [comment]
My concern is that this is already working _with_ the `.` on all 3 platforms in the samples projects, albeit without route parameters. I believe it is also tied to whether we declare the `base` path in the html. So I just want to make sure that I don't break any existing working deployments by removing the dot.
