### ISSUE TITLE
Samples Page Missing some Source Code

### ISSUE THREAD

**Issue by morehavoc** [dymaptic/GeoBlazor#205]
The code is in the repo, but doesn't make it into the published sample app.

As reported via email:

> I was browsing your site [samples.geoblazor.com](http://samples.geoblazor.com/) today and noticed that it seems to be missing some source codes. At least the following pages source code pages appear blank to me:
> - Scenes & Attributes
> - Popups
> - Web Map

**Comment by TimPurdum** [comment]
This has been fixed in our private `Pro` repository where the published samples site is generated from.
