### ISSUE TITLE
ActionButton callback function not getting called when multiple GraphicLayers are defined

### ISSUE THREAD

**Issue by harryPL** [dymaptic/GeoBlazor#242]
Hello.
I've run into an issue where an ActionButton callback function is not getting called. In my example, I've got a basemap and I define the first GraphicLayer in markup. The second GraphicLayer is defined in the code and then added to the map by calling AddLayer().
Graphics of the first layer do not define any actions. The second graphic layer contains a list of points with a PopupTemplate that does have one ActionButton. 
Repro steps:
1. Wait for the map to fully load
2. Click Graphic 1 button
3. Click on the red marker to open popup and then close it.
4. Click Graphic 2 button
5. Click on one of the blue marker to open the popup.
6. Click "Action no.2" button
7. ActionNo2CallbackFunction is not getting called

What's interesting is that when only the second graphic is rendered, the callback is getting called. It's also getting invoked if we first render the second graphic layer and then the first. 

Below is an example of said issue: 
```
<button class="btn btn-primary" @onclick="AddGraphics">Graphic 1</button>
<button class="btn btn-primary" @onclick="AddSecondGraphic">Graphic 2</button>
<MapView @ref="_view" Longitude="_longitude" Latitude="_latitude" Zoom="11" Style="height: 400px; width: 100%;" > 
    <WebMap>
        <PortalItem Id="fae788aa91e54244b161b59725dcbb2a" />
        <GraphicsLayer @ref="_graphicLayer1" Title="Graphic 1"></GraphicsLayer>
    </WebMap>
    <ScaleBarWidget Position="OverlayPosition.BottomLeft" />
    <LayerListWidget Position="OverlayPosition.TopRight" />
</MapView>

@code
{
    private readonly double _latitude = 34.027;
    private readonly double _longitude = -118.805;
    private MapView _view;
    private GraphicsLayer _graphicLayer1;
    
    private async Task ActionNo2CallbackFunction()
    {

        Console.WriteLine("Action2");
    }
    
    private async Task AddGraphics()
    {
        var firstGraphic = new Graphic(new Point(-118.805, 34.027), new SimpleMarkerSymbol(null, new MapColor("red"), 8), new PopupTemplate("Graphic #1"));
        await _graphicLayer1.Add(firstGraphic);
    }

    private async Task AddSecondGraphic()
    {
        var graphics = new List<Graphic>();
        foreach (var num in Enumerable.Range(1, 100))
        {
            var num1 = (double)num / (double)100;
            graphics.Add(new Graphic(new Point(-118.80500+num1, 34.037), new SimpleMarkerSymbol(null, new MapColor("blue"), 8), new PopupTemplate("Graphic #2", actions: new List<ActionBase>()
            {
                new ActionButton("Action no.2", id: $"graphic-2-{num}", callbackFunction: ActionNo2CallbackFunction)
            })));
            
        }
        var secondGraphicLayer = new GraphicsLayer(graphics, "Second Graphic Layer");
        await _view.AddLayer(secondGraphicLayer);
    }
}
```

**Comment by TimPurdum** [comment]
@harryPL thanks for the clear repro! We'll take a look at this as soon as possible. It does sound like a bug in using a code-first GraphicsLayer.

**Comment by harryPL** [comment]
@TimPurdum I've extend the repro steps, since this bug occurs only if you first open the popup from the first layer and then add the second layer.

**Comment by AndersenBell** [comment]
@harryPL We have found the underlying problem and are working on a solution. Thank you for the clear code sample!

**Comment by TimPurdum** [comment]
@harryPL here is a beta nuget package that should have @AndersenBell's fixes in place. We will work on a production release probably in the next few weeks. https://www.nuget.org/packages/dymaptic.GeoBlazor.Core/2.4.1-beta-1
