### ISSUE TITLE
MapView Zoom Resets when OnViewRendered Defined on View

### ISSUE THREAD

**Issue by djrpascu** [dymaptic/GeoBlazor#276]
The zoom value seems to reset when trying to pinch zoom or use zoom controls when the mapview first loads.

Reproduce Issue

- Clone sample repo here: https://github.com/djrpascu/GeoBlazorBugMapViewZoomReset
- Wait for map to load, without panning, try zoom in/out with control, or pinch zoom, the map zoom should reset.

Similar to the issue reported here:
https://github.com/dymaptic/GeoBlazor/issues/188
@TimPurdum 

- Like in the issue above, if you pan the map first, then try zoom controls, the zoom is retained.

- Remove `OnViewRendered="OnViewRendered"` from MapView in MyMapComponent.razor. Try again, and should work.

**Comment by TimPurdum** [comment]
@djrpascu thanks for the clear bug report and repro! I can confirm everything you're seeing. This is definitely a render-cycle issue between GeoBlazor and Blazor, as you discovered by removing `OnViewRendered`. With any luck, I will be able to find a fairly simple fix.

**Comment by djrpascu** [comment]
@TimPurdum thanks for the quick PR on this. will keep an eye out for 2.5.2 and test. mahalo!

**Comment by djrpascu** [comment]
Installed 2.5.2 and confirmed issue is fixed. Much thanks!

**Comment by TimPurdum** [comment]
@djrpascu awesome news!
