### ISSUE TITLE
Unit Test Failures Related to OBJECT_ID in FeatureLayer Tests

### ISSUE THREAD

**Issue by adrien426** [dymaptic/GeoBlazor#306]
## Description
There seems to be a recurring issue with the `OBJECT_ID` attribute when executing `ApplyEdits` in the `FeatureLayer` tests. 
Two tests consistently fail, producing errors indicating that `OBJECT_ID` cannot be read from undefined.

## Steps to Reproduce
1. Execute the `TestCanUpdateManyFeaturesWithApplyEdits` test case.
2. Execute the `TestCanDeleteManyFeaturesWithApplyEdits` test case.

## Expected Behavior
The tests should complete without any errors, successfully updating and deleting multiple features with `ApplyEdits`.

## Actual Behavior
Both tests are failing. The screenshot attached to this issue illustrates the test failures and their associated error messages.

![image](https://github.com/dymaptic/GeoBlazor/assets/9755757/4240deb1-bc75-4a38-bcfb-8d58653594f5)

## Potential Causes
- The `OBJECT_ID` attribute may not be correctly set or passed to the `ApplyEdits` function.
- The features being edited might not be correctly initialized with an `OBJECT_ID`.

**Comment by TimPurdum** [comment]
Should be fixed as part of #313
