### ISSUE TITLE
Expand PictureMarkerSymbol with Base64

### ISSUE THREAD

**Issue by dirk193** [dymaptic/GeoBlazor#311]
Hello,
Is there a way to equip the PictureMarkerSymbol not only with Url, but also with Base64 functionality?

Thank you very much.

**Comment by TimPurdum** [comment]
Hello, @dirk193! Have you tried passing a base64 string as the url? See this post about the ArcGIS SDK, it looks like they got it working: https://community.esri.com/t5/arcgis-javascript-maps-sdk-questions/can-picturemarkersymbol-will-be-able-to-load-image/td-p/537307

**Comment by TimPurdum** [comment]
The key I believe is starting with `data:image/png;base64,` at the front of your base64 data in the url.

**Comment by dirk193** [comment]
Thanks, I could have actually figured that out myself :-)
