### ISSUE TITLE
In "Many Graphics" if one graphic with invalid Url other graphic is not shown too.

### ISSUE THREAD

**Issue by dirk193** [dymaptic/GeoBlazor#312]
Point point = arg.MapPoint;
            var gGrafiks = new List<Graphic>();
            {
                var gGrafik = new Graphic(point);
                gGrafiks.Add(gGrafik);
                //With this line both image is shown
                var ps = new PictureMarkerSymbol("https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png", 15, 15, 0, 0, 0);
                //With this line the image and next image is not shown
                //var ps = new PictureMarkerSymbol("https://github.githubassets.com/anything.png", 15, 15, 0, 0, 0);
                await gGrafik.SetSymbol(ps);
            }
            {
                point = new Point(point.Longitude - 0.1, point.Latitude);
                var gGrafik = new Graphic(point);
                gGrafiks.Add(gGrafik);
                var ps = new PictureMarkerSymbol("https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png", 15, 15, 0, 0, 0);
                await gGrafik.SetSymbol(ps);
            }
            await _graphicsLayer!.Add(gGrafiks);

**Comment by TimPurdum** [comment]
@dirk193 not sure if V3 fixed something here, but running this test in our testrunner, with the following code:

```csharp
GraphicsLayer? layer = null;
AddMapRenderFragment( 
    @<MapView class="map-view" OnViewRendered="renderHandler">
        <Map ArcGISDefaultBasemap="arcgis-imagery">
            <GraphicsLayer @ref="layer" />
        </Map>
    </MapView>);

await WaitForMapToRender();

List<Graphic> newGraphics = [];

Point point = new(0, 0);
Graphic graphic = new Graphic(point);
newGraphics.Add(graphic);
// invalid url
PictureMarkerSymbol ps = new PictureMarkerSymbol("https://github.githubassets.com/anything.png", 
    15, 15, 0, 0, 0);
await graphic.SetSymbol(ps);

point = new Point(point.Longitude - 0.1, point.Latitude);
Graphic graphic2 = new Graphic(point);
newGraphics.Add(graphic2);
PictureMarkerSymbol ps2 = new PictureMarkerSymbol(
    "https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png", 
    15, 15, 0, 0, 0);
await graphic2.SetSymbol(ps2);

await layer!.Add(newGraphics);
await Task.Yield();
await AssertJavaScript("assertGraphicExistsInLayer", args: [layer.Id, "point", 2]);
```
        
I can see the GitHub icon on the map. We get a single error in the console that the first url is invalid, but everything else works.

**Comment by dirk193** [comment]
Hello @TimPurdum  , yes, in version 3 it is fixed. If I had known that version 3 was coming soon, I would have waited for it. ;-)

Thank you very much
