### ISSUE TITLE
NuGet package for v3.0.0 release seems to be missing JS folder/files

### ISSUE THREAD

**Issue by michael-lillo** [dymaptic/GeoBlazor#317]
Updating from v2.5.3.2 to v3.0.0 seems to have broken the Map I was using. When loading the map, it's unable to find arcGisJsInterop.js?v=3.0.0.0. Looking at the content of the nuget package itself, there doesn't seem to be a js folder in _content/dymaptic.GeoBlazor.Core.

Grabbing the js folder from the older version is a workaround for pre-existing maps, but you won't be able to use the ImageryLayer with the older version.

**Comment by TimPurdum** [comment]
@michael-lillo thank you for this report! I have marked 3.0.0 as deprecated and uploaded 3.0.1, should be available shortly.

**Comment by TimPurdum** [comment]
I will use this gissue to track, need to figure out why the automated build pipeline excluded the JS file.

**Comment by TimPurdum** [comment]
Fixed on 5/8
