### ISSUE TITLE
Remove lot of Graphics doesn' work

### ISSUE THREAD

**Issue by dirk193** [dymaptic/GeoBlazor#318]
private async Task RemoveTest()
        {
            if (_graphicsLayer != null)
            {
                //This Code does not work:
                //Think this code would be faster
                await _graphicsLayer!.Remove(_graphicsLayer.Graphics);
                //This Code works:
                foreach (var item in _graphicsLayer.Graphics)
                {
                    await _graphicsLayer!.Remove(item);
                }
            }

        }

**Comment by dirk193** [comment]
Please remove the function "removeGraphics" in "arcGisJsInterop.ts" to 

`export function removeGraphics(graphicWrapperIds: string[], viewId: string, layerId?: string | null): void {
    try {
        setWaitCursor(viewId);
        let view = arcGisObjectRefs[viewId] as View;
        let graphicsToRemove: Graphic[] = [];
        for (const id of graphicWrapperIds) {
            graphicsToRemove.push(graphicsRefs[id]);
            delete graphicsRefs[id];
        }
        if (hasValue(layerId)) {
            let layer = arcGisObjectRefs[layerId as string] as GraphicsLayer;
            layer.removeMany(graphicsToRemove);
        } else {
            view.graphics.removeMany(graphicsToRemove);
        }
        unsetWaitCursor(viewId);
    } catch (error) {
        logError(error, viewId);
    }
}
`

Change the row in function `    public async Task Remove(IEnumerable<Graphic> graphics)
` in "GraphicsLayer.cs":

`        await JsModule!.InvokeVoidAsync("removeGraphics", wrapperIds, View!.Id, Id);
`

thank you

**Comment by TimPurdum** [comment]
@dirk193 just wanted to drop a line and say thank you for the bug reports, and let you know we are tracking, just been very busy. Hopefully can tackle a bunch of these at once in a near future update.

**Comment by TimPurdum** [comment]
@dirk193 this was a bit confusing to follow, but I think I now understand that you are saying the parameters are not matched between the C# invocation and the TypeScript function. I will open a PR to fix that shortly.
