### ISSUE TITLE
Add Many Graphics is doesn't work with TextSymbol with MapFont since Version 3.01

### ISSUE THREAD

**Issue by dirk193** [dymaptic/GeoBlazor#320]
Add in ManyGraphics.razor following Code:

`    private Symbol GenerateText()
    {
        return new TextSymbol(
            "Hello",
            color: new MapColor("red"),
            backgroundColor: new MapColor("transparent")
             , font: new MapFont(12, "Arial", "normal", "bold")
            );
    }
`
In GenerateGraphic add:

`                case "Text":
                    return new Graphic(GeneratePoint(), GenerateText(), GeneratePopupTemplate(),
                        GenerateAttributes());
`
Replace this:

`    <select disabled="@_generating" @bind="_geometryType" @bind:after="SetGraphics">
        <option value="Point">Point</option>
        <option value="Polyline">Polyline</option>
        <option value="Polygon">Polygon</option>
        <option value="Text">Text</option>
    </select>
`

Run it

**Comment by TimPurdum** [comment]
@dirk193 thanks for this, it is a legit bug, will fix shortly!

**Comment by dirk193** [comment]
Thank you
