### ISSUE TITLE
Unable to call `SetVisibility` from a `GraphicsLayer` created in C#

### ISSUE THREAD

**Issue by nwestfall** [dymaptic/GeoBlazor#321]
If I create a `GraphicsLayer` in C# and add it to the `MapView`, I am unable to call `SetVisibility` and I assume other methods that require the `jsModule`.

Doing so, causes the following (tested on Blazor WebAssembly and MAUI Hybrid)
![image](https://github.com/dymaptic/GeoBlazor/assets/4753021/cd3028a2-5aff-482d-841f-8c00a9d187bb)
<img width="1330" alt="image" src="https://github.com/dymaptic/GeoBlazor/assets/4753021/c603f0ae-8149-4a6d-96cb-2a7ccb287d33">

This is the code that fails
```c#
var secondPointsLayer = new GraphicsLayer();
await secondPointsLayer.Add(mapPoints);
await mapView.AddLayer(secondPointsLayer);

await secondPointsLayer.SetVisibility(false); // ERRORS
```

By adding the following line before `SetVisibility`, the code works as expected
```c#
var secondPointsLayer = new GraphicsLayer();
await secondPointsLayer.Add(mapPoints);
await mapView.AddLayer(secondPointsLayer);

secondPointsLayer.JsModule = mapView.JsModule; // ADD THIS LINE
await secondPointsLayer.SetVisibility(false); // WORKS AS EXPECTED
```

I'm happy to attempt to fix this, my first though is to check the module when `AddLayer` is called and if `null`, just set it - https://github.com/dymaptic/GeoBlazor/blob/1b8985a67ced91e3eb1a48138b1d8cebf346a207/src/dymaptic.GeoBlazor.Core/Components/Views/MapView.razor.cs#L1286-L1312

If you need a sample project, let me know.  Tested with v3.0.1

**Comment by CyberDNS** [comment]
Hi @nwestfall ,

We detected the same issue and already prepared a fix for it, I will create a pull request today to suggest a fix for the problem. 
The developer that implemented the fix confirms that the fix is pretty the same than you suggestion.

Br, 
David from POST Technologies Luxembourg

**Comment by TimPurdum** [comment]
@nwestfall @CyberDNS thanks for the report and the work on fixes. I concur with the path of fixing this, checking out the PR shortly.
