### ISSUE TITLE
Map is showing but broken

### ISSUE THREAD

**Issue by DTemeroso** [dymaptic/GeoBlazor#323]
Since I upgraded to version 3.0.1, the map looks like this:

![image](https://github.com/dymaptic/GeoBlazor/assets/160488451/f532d700-4be9-43d6-afbb-5c1ac02e35c4)

And when he went to see the errors and warnings, the warning of "version mismatch detected"
![image](https://github.com/dymaptic/GeoBlazor/assets/160488451/60ea159d-1b6c-4e75-a399-a415449c7a54)

I don't know if with the update I have to change the position of a few lines of code or something else.

**Comment by TimPurdum** [comment]
Hi @DTemeroso, for the warning, try setting `disable cache` in your browser dev tools. If that fixes it, and this is an issue for end users, then we need to figure out how to force a cache refresh for them as well. We use a version query `arcGisJsInterop.js?v=3.0.1` for our JS file to avoid this, but not sure on how to tackle that for the big set of ArcGIS assets.

The other thing that could be causing the visual issue you see is this breaking change:

> The order of Layers added to the map in Razor markup has been inverted. Now, the topmost layer in Razor markup will be on top in the map view. For multi-layered scenarios, you will likely need to reverse the order in your Razor code.

https://github.com/dymaptic/GeoBlazor/releases/tag/v3.0.1

**Comment by DTemeroso** [comment]
Thank you. I just needed to disable cache in the development tools.
