### ISSUE TITLE
TakeScreenshot API

### ISSUE THREAD

**Issue by mfrezza** [dymaptic/GeoBlazor#347]
Hi, 
I wonder if is there a way to trigger the api function to take screenshot of a mapview (https://developers.arcgis.com/net/wpf/sample-code/take-screenshot/) and/or a scene view (https://developers.arcgis.com/javascript/latest/sample-code/sceneview-screenshot/). 

Alternatively, is it planned to be implemented in a future release? 

Thank you in advance, 

Mattia

**Comment by TimPurdum** [comment]
Hi @mfrezza! I definitely would like to add this feature in the near future, so we'll leave this open. In the meantime, a quick JS extension would do the trick.

```js
export async function takeArcGisScreenshot(coreModule, viewId) {
    let view = coreModule.arcGisObjectRefs[viewId];
    let screenshot = await view.takeScreenshot();
    return base64ToArrayBuffer(screenshot.dataUrl.split(",")[1]);
}

// Converts a base64 string to an ArrayBuffer
function base64ToArrayBuffer(base64) {
    const binaryString = atob(base64);
    const bytes = new Uint8Array(binaryString.length);
    for (let i = 0; i < binaryString.length; i++) {
        bytes[i] = binaryString.charCodeAt(i);
    }
    return bytes.buffer;
}
```

and called from C#:

```csharp
IJSStreamReference jsStreamRef = await JsModule!.InvokeAsync<IJSStreamReference>("takeArcGisScreenshot", MapView.JsModule, MapView.Id);
Stream mapStream = await jsStreamRef.OpenReadStreamAsync(1_000_000_000L);
