### ISSUE TITLE
Add an ImageryLayer

### ISSUE THREAD

**Issue by TimPurdum** [dymaptic/GeoBlazor#66]
[ImageryLayer](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-ImageryLayer.html)

1. Add the `ImageryLayer`
2. Add the layer to `LayerTypes.razor` created in #63. Alternatively, if these are too different, create a new samples page.

**Comment by TimPurdum** [comment]
Good layer to use for sample : https://moraveclabsllc.maps.arcgis.com/home/item.html?id=a1ba14d09df14f42ad6ca3c4bcebf3b4

**Comment by seahro** [comment]
The dotnet renderers associated with this layer are in GeoBlazor.Pro.  
Reference: https://github.com/dymaptic/GeoBlazor.Pro/issues/59 
The sample and javascript methods are in this repo.
