### ISSUE TITLE
Question on geoblazor

### ISSUE THREAD

**Issue by Shawn-Fan** [dymaptic/GeoBlazor#78]
Thanks for the great framework for the Gis project. I have several questions for it.
1. As per introduction , there are two types of libraries, Arcgisinteractive.js and arcgisjsinterop.js. Are they the same one?
2. From the mapview.razor.cs file, if the renderview doesn’t work properly (for example, the interaction with the server can not work and didn’t get the result) it will continue work forever…, is it designed on purpose?

thanks

**Comment by TimPurdum** [comment]
Hi @Shawn-Fan! Thanks for checking out GeoBlazor, and the questions. I'll try my best to answer.

1. `arcGisJsInterop.js` should be all you need/use right now if you are using this library or nuget package. `arcGisInteractive` is actually defined in a separate, private repository where we are working on potential future extensions to build on top of GeoBlazor. These will hopefully be offered as an affordable package to developers, similar to how companies offer UI component libraries (e.g. Telerik, SyncFusion, DevExpress). But we also plan to keep expanding this core library as a free offering to the community.
Further, the JavaScript files are intended to be mostly "hidden" by this library, and ideally you wouldn't need to refer to them directly unless you are doing something advanced. Instead, the library does all those calls for you, and exposes C#/Razor components to use directly.

2. I believe if you get an error such as a connection issue when rendering the mapview, it should surface this error to your debugger as well as the UI, and stop processing. We could add more retry type logic and handling, but I'm not sure exactly what error you're seeing? I haven't experienced anything getting "stuck" thus far myself, but if you have an example, let me know!

**Comment by Shawn-Fan** [comment]
Thanks for your quick response.
1. I understand "arcGisInteractive" is the big map for the future gis development from your explanation. I also knew the "arcGisJsInterop.js" form the "arcGisJsInterop.ts" file.
2. I just run the "dymaptic.GeoBlazor.Core.Sample.Wasm" project. added several "console.writeLine(....)" in "MapComponent.razor.cs", "Mapview.razor.cs", "Map.cs", and some lines to "onAfterRenderAsync", "RenderView" in apView.razor.cs. Running the project, select "Navigation" , console displaying as follow:

_1.    Failed to load resource: net::ERR_INTERNET_DISCONNECTED
2. blazor.webassembly.js:1 Debugging hotkey: Shift+Alt+D (when application has focus)
3. Debugging hotkey: Shift+Alt+D (when application has focus)
4. blazor.webassembly.js:1 blazor Loaded 10.31 MB resourcesThis application was built with linking (tree shaking) disabled. Published applications will be significantly smaller.
5. blazor.webassembly.js:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://localhost:7143/_content/dymaptic.GeoBlazor.Core.Sample.Shared/css/open-iconic/font/fonts/open-iconic.woff
6. blazor.webassembly.js:1 mapview--OnInitialized called
7. blazor.webassembly.js:1 map--OnInitialized called
8. 2blazor.webassembly.js:1 mapcomponent--OnInitialized called
9. 2blazor.webassembly.js:1 Runing RenderViewing...
10. blazor.webassembly.js:1 Running OnAfterRenderAsync
11. blazor.webassembly.js:1 Runing RenderViewing...
12. blazor.webassembly.js:1 Running OnAfterRenderAsync --if (NeedsRender)
13. blazor.webassembly.js:1 Running OnAfterRenderAsync
14. blazor.webassembly.js:1 Runing RenderViewing...
15. blazor.webassembly.js:1 Running OnAfterRenderAsync --if (NeedsRender)
16. blazor.webassembly.js:1 Running OnAfterRenderAsync
17. blazor.webassembly.js:1 Runing RenderViewing...
18. blazor.webassembly.js:1 Running OnAfterRenderAsync --if (NeedsRender)
19. blazor.webassembly.js:1 Running OnAfterRenderAsync
20. blazor.webassembly.js:1 Runing RenderViewing...
21. blazor.webassembly.js:1 Running OnAfterRenderAsync --if (NeedsRender)
22. blazor.webassembly.js:1 Running OnAfterRenderAsync
23. blazor.webassembly.js:1 Runing RenderViewing
24. ...
25. ...
26. same as line 21-23
27. ...
28. ..._

line 1 is ok, because I just want to test the browser and I run the code offline. 
from line 12 on, it keeps on running because "NeedsRendering" is always true(default).  it will not run 
...
        _await InvokeAsync(async () =>
        {
            Console.WriteLine("Rendering View");
            string mapType = Map is null ? "webmap" : "map";
            object? map = Map is null ? WebMap : Map;

            if (map is null)
            {
                throw new MissingMapException();
            }

            NeedsRender = false;

            await ViewJsModule!.InvokeVoidAsync("buildMapView", Id,
                DotNetObjectReference, Longitude, Latitude, Rotation, map, Zoom, Scale,
                ApiKey, mapType, Widgets, Graphics, SpatialReference);
            Rendering = false;
            _newPropertyValues.Clear();
            MapRendered = true;
        });_
...
 so this the the question I asked last time.

Thanks in advance!

**Comment by TimPurdum** [comment]
@Shawn-Fan, thank you for the error details.

GeoBlazor is a web application, that depends on the ArcGIS JavaScript API, which performs many calls over the internet. As such, we are not able to support an offline mode. If you want this application to work, you will have to turn on your internet connection. We can certainly improve our error message to make this clearer in the future and prevent the retry loop from running after a certain timeout if the application is offline, but you won't see any maps or features even so.

The only developer tool for building offline applications with ArcGIS is the [ArcGIS Runtime API](https://developers.arcgis.com/net/), which supports mobile and desktop applications, but not web applications. If this is your need, I suggest you take a look at that route. In the future, we'd love to look at expanding GeoBlazor with an offline mode for Blazor Hybrid (MAUI) applications, but this is not a near-term goal.

I hope that helps!

**Comment by Shawn-Fan** [comment]
Thanks for your response, After debugging the source code I found the bug is from line 15, because it causes the component to be re-rendered.

1.     /// <inheritdoc />
2.     protected override async Task RenderView(bool forceRender = false)
3.     {
4.         if (!NeedsRender && !forceRender)
5.         {
6.             return;
7.         }
8. 
9.         if (Rendering || (Map is null && WebMap is null) || ViewJsModule is null) return;
10. 
11.         if (string.IsNullOrWhiteSpace(ApiKey) && (AllowDefaultEsriLogin is null || !AllowDefaultEsriLogin.Value))
12.         {
13.             ErrorMessage = "No ArcGIS API Key Found. See UsingTheAPI.md for instructions on providing an API Key or suppressing this message.";
14.             System.Diagnostics.Debug.WriteLine(ErrorMessage);
15.             StateHasChanged();
16. 
17.             return;
18.         }
19. 
20.         Rendering = true;
21.         ValidateRequiredChildren();
22. 
23.         await InvokeAsync(async () =>
24.         {
25.             Console.WriteLine("Rendering View");
26.             string mapType = Map is null ? "webmap" : "map";
27.             object? map = Map is null ? WebMap : Map;
28. 
29.             if (map is null)
30.             {
31.                 throw new MissingMapException();
32.             }
33. 
34.             NeedsRender = false;
35. 
36.             await ViewJsModule!.InvokeVoidAsync("buildMapView", Id,
37.                 DotNetObjectReference, Longitude, Latitude, Rotation, map, Zoom, Scale,
38.                 ApiKey, mapType, Widgets, Graphics, SpatialReference);
39.             Rendering = false;
40.             _newPropertyValues.Clear();
41.             MapRendered = true;
42.         });
43.     }
