### ISSUE TITLE
Improve error handling around internet disconnect

### ISSUE THREAD

**Issue by TimPurdum** [dymaptic/GeoBlazor#87]
#78 raised a question about "offline" mode. While we can't support that in the near future (it is a limitation of the ArcGIS JS API), we can improve error handling if the browser detects that it is offline.

1. Expose a clear, human-readable exception when the browser detects that it is offline.
2. Stop spamming recurring messages from an incomplete circuit.
3. Implement actual retry logic. This could be just a few hard-coded retries for now, to be extended to something configurable in the future.

**Comment by Shawn-Fan** [comment]
@TimPurdum 
I am wondering the limitation of the ArcGIS JS API, Could you let me know the limitation?

**Comment by morehavoc** [comment]
The ArcGIS JavaScript API is kind of inherently an online API. For one it's JavaScript, although I guess these days that's not much of an argument for online only! For two, it heavily depends on the basemap, and that has to be online. It does do local caching though, so it should be able to survive being offline for a time and then going online again, however you won't be able to query hosted services etc.

Esri technically doesn't support any offline workflows with JS, they have lots of other APIs for that (more info [here](https://developers.arcgis.com/documentation/mapping-apis-and-services/offline/#api-support)).

I suppose a more advanced use case we might want to consider is starting online, going offline, and then coming back online. But... maybe that's best handled in an individual app where you could save changes to local storage and then re-load them yourself etc.

There might be ways around certain limitations though, @Shawn-Fan  could you share more about the problem you are trying to solve or your use case?

**Comment by morehavoc** [comment]
After further discussion, it might be possible to make this kind of work, see notes in this PR: https://github.com/dymaptic/GeoBlazor/pull/95#discussion_r1003823676

If all that works, I was wrong about needing the basemap above.

@Shawn-Fan We'd still like for you to explain your use case more though!

**Comment by Shawn-Fan** [comment]
@morehavoc 
Thanks for your response, I am interested in the Geoblazor library and do some research on it.
As what you mentioned 
"_... it heavily depends on the basemap, and that has to be online. It does do local caching though, so it should be able to survive being offline for a time and then going online again.._"  
 That's true!

 "_however you won't be able to query hosted services etc._"  
 Why?

"_Esri technically doesn't support any offline workflows with JS..._"
 I am wondering what the " offline workflows with JS" means? From my understanding, each project(it doesn't matter blazor(server,wasm), web, desktop,...) it should connect to server and do some work(load map tile, data) as need. 

I am wondering if i am understand your question, Thanks,

**Comment by morehavoc** [comment]
> "however you won't be able to query hosted services etc."
> Why?

By Hosted Feature Services, I mean data that is hosted in ArcGIS Online other than basemaps, data that you created or that someone provided to you that you want to consume in the app. If the app is "offline" then it won't be able to query that data. Same as if the app is "offline" then it won't be able to load basemaps.

When I say "offline" I mean that the browser doesn't have a connection to the internet, so it couldn't load basemaps or other services from ArcGIS Online. Esri provides the "runtime" SDKs that allow you to download data and work with it "offline" (no internet connection. The JS API does not allow you download data in the same way.

@Shawn-Fan  Could you tell us more about what you are wanting to do?

**Comment by Shawn-Fan** [comment]
@morehavoc Thanks for your response, I solved the problem i met already.
