### ISSUE TITLE
Return Geometry from View Click Event

### ISSUE THREAD

**Issue by TimPurdum** [dymaptic/GeoBlazor#90]
Brought up during [this Discord discussion](https://discord.com/channels/1027907220949717033/1031452704167432222), and user `Sipowicz` even provided some sample implementation. 

Add the ability to return a geometry (point, line, polygon) when clicking on that geometry on the map. This would be similar to the current `MapView.OnClickAsyncHandler`, which returns the `Point` where you clicked, but instead it would return a `Geometry` (or maybe `Graphic`?) if there is a graphic at the spot clicked.

Furthermore, when this is handled in the JS, we could probably look up the graphic in `arcGisObjectRef` and find the original .NET object, and append the `Id` to the return object.

@morehavoc if you have any thoughts to add...

**Comment by morehavoc** [comment]
I think that the standard JS way to get "features" by clicking on the map is:

1. Listen for a click on the MapView: https://developers.arcgis.com/javascript/latest/api-reference/esri-views-MapView.html#event-click
2. This even returns a MouseEvent (click event) object (more than just the geometry) that tells you where the click was on the screen as well as on the earth. You can pass this even directly into `hitTest`
3. Then call `hitTest()` https://developers.arcgis.com/javascript/latest/api-reference/esri-views-MapView.html#hitTest
4. This returns an array of objects. These objects can vary in type, although it looks like it's basically just `Graphic` and "media". https://developers.arcgis.com/javascript/latest/api-reference/esri-views-MapView.html#HitTestResult

We could wrap this up in a single event, but I kind of think we should duplicate the JS API first. So expand the current `OnClickAsyncHandler` to return more than just a Geometry and then implement the `HitTestAsync` function.

For `hitTest` we could start by only supporting the Graphics returned if that made things much simpler, but we'd want to log a gissue to remember we did that. We probably do need to support the optional parameter here that allow you to configure what you are getting back in the hit test though.

**Comment by TimPurdum** [comment]
@morehavoc thanks, I defer to your idea. I didn't realize `hitTest` was really it's "own thing" there, that would have other uses outside of the click handler. I agree, we should implement these separately, and then show people how to chain them.
