### ISSUE TITLE
Getting Started Documentation Missing Information

### ISSUE THREAD

**Issue by morehavoc** [dymaptic/GeoBlazor#98]
The getting started docs are missing some of the content we used to have in the ReadMe.md file. Mainly, the information about setting up the API key, and what parameters it needs to have.

The code is also incomplete, it references a `_latitude` and `_longitude` properties that are not defined anywhere.

**Comment by TimPurdum** [comment]
@morehavoc the API key info was moved to the `Authentication` page, and step 4 in `Getting Started` has a link. I'm open to suggestions on reworking that if it's confusing, but I also don't really want to duplicate info too much.

I'll replace the lat/long variables with just numbers, once we've discussed the other change.

**Comment by morehavoc** [comment]
I want the Getting Started Docs to be so simple that folks can basically follow it without having to think about it too much. Also, it should be a one-stop page for someone that has used the library before but needs to be reminded how to get it setup again. So, I don't think we should hid Authentication behind a link, we need to have some minimum text in this doc.

(I also think we should bump authentication up to step 3, that way once you start with the copy and paste of code, it's not interrupted by this which might require thought, but shouldn't really require thought if you are just trying to try it out.)

So we could make the authentication part something like: 

4. The ArcGIS API requires some form of [authentication](https://docs.geoblazor.com/pages/authentication). The simplest is to use an API Key. Configure that at [ArcGIS Developers](https://developers.arcgis.com/documentation/mapping-apis-and-services/security/api-keys) and place it in your `appsettings.json`, like this:

```
{
    "ArcGISApiKey": "yourKeyValue"
}
```

**Note:** If you are using Blazor WASM, be aware that the API key will be exposed in the browser (just like it would with Javascript). Even when using Blazor Server, the API key may be present in HTTP requests visible to the user in the browsers dev tools, so you should probably take other steps like setting up [referrer rules in ArcGIS](https://developers.arcgis.com/documentation/mapping-apis-and-services/security/api-keys/#referrers).

You can also setup an OAuth2 workflow, which is more secure as it does not expose a static API key, but this is more complex. You can read about all the authentication options [here](https://docs.geoblazor.com/pages/authentication).
